language: go

go:
  - '1.16'

script: go test -v ./...

env:
  - CODECOV_TOKEN="f679d816-f33f-45a4-8275-ff39c05218d8"

before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
